title: Tools and Techniques for Computational Economics
author: Thomas J. Sargent and John Stachurski
logo: _static/qe-logo-large.png
description: This website presents a set of lectures on the tools and techniques required to study computational economics.

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

only_build_toc_files: true
execute:
  execute_notebooks: "cache"
  timeout: 2400

bibtex_bibfiles:
   - _static/quant-econ.bib

html:
  baseurl: https://tools-techniques.quantecon.org/

latex:
   latex_documents:
      targetname: quantecon-tools-techniques.tex

sphinx:
  extra_extensions: [sphinx_multitoc_numbering, sphinxext.rediraffe, sphinx_tojupyter, sphinxcontrib.youtube, sphinx.ext.todo, sphinx_exercise, sphinx_togglebutton, sphinx.ext.intersphinx, sphinx_reredirects]
  config:
    nb_mime_priority_overrides: [
       # HTML
       ['html', 'application/vnd.jupyter.widget-view+json', 10],
       ['html', 'application/javascript', 20],
       ['html', 'text/html', 30],
       ['html', 'text/latex', 40],
       ['html', 'image/svg+xml', 50],
       ['html', 'image/png', 60],
       ['html', 'image/jpeg', 70],
       ['html', 'text/markdown', 80],
       ['html', 'text/plain', 90],
       # Jupyter Notebooks
       ['jupyter', 'application/vnd.jupyter.widget-view+json', 10],
       ['jupyter', 'application/javascript', 20],
       ['jupyter', 'text/html', 30],
       ['jupyter', 'text/latex', 40],
       ['jupyter', 'image/svg+xml', 50],
       ['jupyter', 'image/png', 60],
       ['jupyter', 'image/jpeg', 70],
       ['jupyter', 'text/markdown', 80],
       ['jupyter', 'text/plain', 90],
       # LaTeX
       ['latex', 'text/latex', 10],
       ['latex', 'application/pdf', 20],
       ['latex', 'image/png', 30],
       ['latex', 'image/jpeg', 40],
       ['latex', 'text/markdown', 50],
       ['latex', 'text/plain', 60],
       # Link Checker
       ['linkcheck', 'text/plain', 10],
     ]
    html_favicon: _static/lectures-favicon.ico
    html_theme: quantecon_book_theme
    html_static_path: ['_static']
    html_theme_options:
      authors:  
        - name: Thomas J. Sargent
          url: http://www.tomsargent.com/
        - name: John Stachurski
          url: https://johnstachurski.net/
      header_organisation_url: https://quantecon.org
      header_organisation: QuantEcon
      repository_url: https://github.com/QuantEcon/lecture-tools-techniques
      nb_repository_url: https://github.com/QuantEcon/lecture-tools-techniques.notebooks
      twitter: quantecon
      twitter_logo_url: https://assets.quantecon.org/img/qe-twitter-logo.png
      og_logo_url: https://assets.quantecon.org/img/qe-og-logo.png
      description: This website presents a set of lectures on the tools and techniques required to study computational economics.
      keywords: Python, QuantEcon, Quantitative Economics, Economics, Sloan, Alfred P. Sloan Foundation, Tom J. Sargent, John Stachurski
      analytics:
        google_analytics_id: G-FH5JZQ6T4G
      launch_buttons:
        colab_url                 : https://colab.research.google.com
    intersphinx_mapping:
      pyprog:
        - https://python-programming.quantecon.org/
        - null
      intro: 
        - https://intro.quantecon.org/
        - null
      dle:
        - https://quantecon.github.io/lecture-dle/
        - null
      dps:
        - https://quantecon.github.io/lecture-dps/
        - null
      eqm:
        - https://quantecon.github.io/lecture-eqm/
        - null
      stats:
        - https://quantecon.github.io/lecture-stats/
        - null
      tools:
        - https://quantecon.github.io/lecture-tools-techniques/
        - null
      dynam:
        - https://quantecon.github.io/lecture-dynamics/
        - null
    mathjax3_config:
      tex:
        macros:
          "argmax" : "arg\\,max"
          "argmin" : "arg\\,min"
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    # Local Redirects
    rediraffe_redirects:
      index_toc.md: intro.md
    # Remote Redirects
    # redirects:
    #   heavy_tails: https://intro.quantecon.org/heavy_tails.html
    tojupyter_static_file_path: ["source/_static", "_static"]
    tojupyter_target_html: true
    tojupyter_urlpath: "https://tools-techniques.quantecon.org/"
    tojupyter_image_urlpath: "https://tools-techniques.quantecon.org/_static/"
    tojupyter_lang_synonyms: ["ipython", "ipython3", "python"]
    tojupyter_kernels:
      python3:
        kernelspec:
          display_name: "Python"
          language: python3
          name: python3
        file_extension: ".py"
    tojupyter_images_markdown: true
